include: 'http://platform.pages.twogether.io/cicd/templates/staticsite.gitlab-ci.yml'

variables:
  PUBLIC_URL: https://$CI_PROJECT_NAMESPACE.pages.twogether.io/$CI_PROJECT_NAME/
  REACT_APP_BASENAME: /$CI_PROJECT_NAME

cache:
  paths:
    - ./node_modules

build:
  image: node:18-alpine
  stage: build
  script:
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - build
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

pages:
  before_script:
    - rm -rf public
    - mv build public
