include: http://platform.pages.twogether.io/cicd/templates/react.gitlab-ci.yml

variables:
  PUBLIC_URL: https://match.twogether.io
  REACT_APP_BASENAME: ''

deploy to prod:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
